### PR TITLE
fix: wait server firewall actions to settle

### LINKED ISSUE #205: Possible race condition related to `rescue` and `upgrade_server_type` options
#### Overview of the Issue

When performing Packer builds with configuration that makes use of the `rescue` and/or `upgrade_server_type` options, the build will occasionally fail with an error like `Could not enable rescue mode: cannot perform operation because server is locked (locked, 59f51b507a355430)`.

However, this does not always happen (right now I'm unable to produce it while it was plaguing me all afternoon, which makes me think it might be related to something something system load during working hours). I feel like the firewall label selector thing might be relevant here, does Hetzner Cloud "lock" an instance when rules are applied, using some kind of worker queue? That'd explain the intermittent nature of the problem I've been seeing. I'm not terribly familiar with the Hetzner Cloud APIs, but if an `action` fails, shouldn't the Packer Plugin retry-backoff, rather than waiting for a result once and considering errors a terminal state?

#### Reproduction Steps

Run the provided Packer Buildfile until you encounter an error.

### Plugin and Packer version

```
Packer v1.11.0
Plugin v1.5.2
```

### Simplified Packer Buildfile

```hcl
# test.pkr.hcl

packer {
  required_plugins {
    hcloud = {
      version = "1.5.2"
      source  = "github.com/hetznercloud/hcloud"
    }
  }
}

source "hcloud" "test" {
  location = "fsn1"
  image  = "debian-12"
  rescue = "linux64"
  server_type = "cpx11"
  upgrade_server_type = "cpx31"
  ssh_username = "root"
  server_labels = {
    "allow-icmp"            = "" # Used to trigger assignment of a firewall rule that allows inbound ICMP
    "allow-ssh"             = "" # Used to trigger assignment of a firewall rule that allows inbound TCP connections to port 22 (SSH)
  }
}

build {
  name = "test"

  sources = ["source.hcloud.test"]

  provisioner "shell" {
    inline = [
      "echo hello",
    ]
  }
}
```

### Operating system and Environment details

```shell_session
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Log Fragments and crash.log files

I'll include logs when I try reproducing the problem again next week.

### PR DESCRIPTION
**Pull request by jooola**
Closes #205

Prevents a server `locked` error from the API, when trying to change the type of the server, while `firewall_apply` are still running in the backend.

The `firewall_apply` actions are triggered by label selectors.

### CODE REVIEW

File: builder/hcloud/step_create_server.go [hunk 1]
```diff
@@ -142,6 +143,16 @@ func (s *stepCreateServer) Run(ctx context.Context, state multistep.StateBag) mu
...
 
+	// Wait that the server to settle before continuing. Prevents possible `locked`
+	// error when changing the server type.
+	actions, err := getServerRunningActions(ctx, client, server)
+	if err != nil {
+		return errorHandler(state, ui, "Could not fetch server running actions", err)
+	}
+	if err := client.Action.WaitFor(ctx, actions...); err != nil {
+		return errorHandler(state, ui, "Could not wait for server running actions", err)
+	}
```
Comment (apricote) [inline builder/hcloud/step_create_server.go:154]: As this is a nice-2-have, we could also log a warning and just continue here.

**Review by apricote — APPROVED** [review]

File: builder/hcloud/step_create_server.go (hunk 1 above)
Comment (jooola) [reply builder/hcloud/step_create_server.go:154]: I am not sure if it is "nice to have", I'd rather say it required for the use cases we propose: making sure a firewall is applied before running further actions on the server.
