### PR TITLE
fix: check if the image was found

### LINKED ISSUE #222: Packer Crash when `image` cannot be found
#### Overview of the Issue

When the base image for sources cannot be found, Packer crashes with SIGSEGV instead of a usable error message.

#### Reproduction Steps

Given this template, Packer will crash on build:
```hcl
source "hcloud" "aarch64" {
  image = "fedora-38"
}
```

Note that the `fedora-38` image does not exist anymore.

### Plugin and Packer version

Packer v1.11.2

v1.5.4 of this plugin

### Simplified Packer Buildfile

https://github.com/mhutter/hcloud-packer-coreos/blob/60deb2515edd6f71679c2b9ab295beba1aede9b7/template.pkr.hcl

### Operating system and Environment details

Linux, x64

### Log Fragments and crash.log files

See https://github.com/mhutter/hcloud-packer-coreos/actions/runs/10372210073/job/28714404526

### PR DESCRIPTION
**Pull request by jooola**
A nil check was missing before using the image object.

Closes #222

### CODE REVIEW

File: builder/hcloud/step_create_server.go [hunk 1]
```diff
@@ -59,13 +59,23 @@ func (s *stepCreateServer) Run(ctx context.Context, state multistep.StateBag) mu
 		if err != nil {
 			return errorHandler(state, ui, "Could not find image", err)
 		}
+		if image == nil {
+			return errorHandler(state, ui, "", fmt.Errorf("Could not find image"))
+		}
```
Comment (apricote) [inline builder/hcloud/step_create_server.go:76]: Can you add a test case to ensure that this does not regress?

**Review by apricote — CHANGES_REQUESTED** [review]

File: builder/hcloud/step_create_server.go (hunk 1 above)
Comment (jooola) [reply builder/hcloud/step_create_server.go:76]: Done

**Review by apricote — APPROVED** [review]
